---
- name: Check dnsdist_repo_provider
  fail: msg="dnsdist_repo_provider is neither 'powerdns' nor 'os'"
  when: dnsdist_repo_provider not in ["os", "powerdns"]

- name: Add the dnsdist YUM repository
  get_url:
    url: https://repo.powerdns.com/repo-files/{{ ansible_distribution | lower() }}-dnsdist-{{ dnsdist_repo_branch }}.repo
    dest: /etc/yum.repos.d/dnsdist-{{ dnsdist_repo_branch }}.repo
  when: dnsdist_repo_provider == "powerdns"

- name: Install epel-release
  yum: name=epel-release state=latest
  when: dnsdist_repo_provider == "powerdns"

- name: Install the latest dnsdist package
  yum: name=dnsdist state=latest
  when: dnsdist_version == 'latest'

- name: Install the dnsdist package version {{dnsdist_version}}
  yum: name="dnsdist={{dnsdist_version}}" state=installed update_cache=yes
  when: dnsdist_version != 'latest'
