---
- name: Check dnsdist_repo_provider
  fail: msg="dnsdist_repo_provider is neither 'powerdns' nor 'os'"
  when: dnsdist_repo_provider not in ["os", "powerdns"]

- name: Add the dnsdist repository key (master)
  apt_key: url=http://repo.powerdns.com/CBC8B383-pub.asc id=D47975F8DAE32700A563E64FFF389421CBC8B383
  when: dnsdist_repo_provider == "powerdns" and dnsdist_repo_branch == "master"

- name: Add the dnsdist repository key (release)
  apt_key: url=http://repo.powerdns.com/FD380FBB-pub.asc id=9FAAA5577E8FCF62093D036C1B0C6205FD380FBB
  when: dnsdist_repo_provider == "powerdns" and dnsdist_repo_branch in ["10"]

- name: apt-pin the dnsdist packages to the dnsdist repo
  copy: dest='/etc/apt/preferences.d/dnsdist' src=dnsdist.pin owner=root group=root mode=0644
  when: dnsdist_repo_provider == "powerdns"

- name: Add the dnsdist repository
  apt_repository: repo="deb http://repo.powerdns.com/{{ansible_lsb.id | lower}} {{ansible_distribution_release|lower}}-dnsdist-{{dnsdist_repo_branch}} main"
  when: dnsdist_repo_provider == "powerdns"

- name: Install the latest dnsdist package
  apt: name=dnsdist state=latest update_cache=yes
  when: dnsdist_version == 'latest'

- name: Install the dnsdist package version {{dnsdist_version}}
  apt: name="dnsdist={{dnsdist_version}}" state=installed update_cache=yes
  when: dnsdist_version != 'latest'
