---
- block:
    - name: Install epel-release on CentOS
      package:
        name: epel-release
        state: present
      when: ansible_distribution in [ 'CentOS' ]

    - name: Install epel-release on RHEL/OracleLinux
      package:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
      when: ansible_distribution in [ 'RedHat', 'OracleLinux' ]

  when: dnsdist_install_epel

- name: Install yum-plugin-priorities
  package:
    name: yum-plugin-priorities
    state: present
  when: ansible_distribution in [ 'CentOS' ] and ansible_pkg_mgr in [ 'yum' ]

- name: Add the dnsdist YUM Repository
  yum_repository:
    name: "{{ dnsdist_install_repo['name'] }}"
    file: "{{ dnsdist_install_repo['name'] }}"
    description: PowerDNS dnsdist Repository
    baseurl: "{{ dnsdist_install_repo['yum_repo_baseurl'] }}"
    gpgkey: "{{ dnsdist_install_repo['gpg_key'] }}"
    gpgcheck: true
    priority: "90"
    state: present

- name: Add the dnsdist debug symbols YUM Repository
  yum_repository:
    name: "{{ dnsdist_install_repo['name'] }}-debuginfo"
    file: "{{ dnsdist_install_repo['name'] }}"
    description: PowerDNS dnsdist Repository - debug symbols
    baseurl: "{{ dnsdist_install_repo['yum_debug_symbols_repo_baseurl'] }}"
    gpgkey: "{{ dnsdist_install_repo['gpg_key'] }}"
    gpgcheck: true
    priority: "90"
    state: present
  when: dnsdist_install_debug_symbols_package
